Issue 160
rhd-gitops-example/odo pull request #122
Opened 2020-06-17 19:50 UTC by gaganeggday

**What type of PR is this?**
> kind cleanup

**What does does this PR do / why we need it**:
Changes the --manifest flag to the --pipelines-file which is more representative of the action it performs.

**Which issue(s) this PR fixes**:
https://issues.redhat.com/browse/GITOPS-160

2020-06-18 02:26 UTC, wtam2018 approved these changes

2020-06-18 11:50 UTC, bigkevmcd commented
I'd prefer to have seen use of the `PersistentFlags` and `TraverseChildren` mechanism, rather than duplicating it across _every_ command.

2020-06-18 11:51 UTC, bigkevmcd commented
See https://github.com/spf13/cobra#persistent-flags, https://github.com/spf13/cobra#local-flag-on-parent-commands and https://github.com/spf13/cobra#bind-flags-with-config

2020-06-19 03:12 UTC, wtam2018 commented on pkg/odo/cli/pipelines/environment/add.go
AddEnvParameters should stay in add.go and should not be moved to environment.go.

2020-06-19 03:13 UTC, wtam2018 commented on pkg/odo/cli/pipelines/environment/add.go
> +			fmt.Println("These are the pipelines and env-name", o.pipelinesFile, o.envName)
Please delete.

2020-06-19 03:16 UTC, wtam2018 commented on pkg/odo/cli/pipelines/environment/add.go
> -	addEnvCmd.Flags().StringVar(&o.manifest, "manifest", "pipelines.yaml", "path to manifest file")
Actually, environment command has only one child (add) command).   I would not worry about using Persistent Flag here.   I would revert changes to environment comment.

2020-06-19 03:18 UTC, wtam2018 commented on pkg/odo/cli/pipelines/service/service.go
> +	// _ = cmd.MarkFlagRequired("env-name")
Like environment command, service ocmmand only has one child.  Let's revert these changes.

2020-06-19 04:12 UTC, wtam2018 requested changes
Need to rebase and PR to `pipelines_feature`

2020-06-19 13:01 UTC, closed without merging