Integration of bootstrap with wizard support for both cli/interactive…
rhd-gitops-example/odo pull request #179
Opened 2020-08-27 07:23 UTC by gaganhegde

**What type of PR is this?**
> /kind design

**What does does this PR do / why we need it**:
Allows users to use both the interactive and the cli mode of command line. 
The previous wizard cli has now been integrated into bootstrap.

Run ./odo pipelines bootstrap to trigger interactive mode, just pass a flag to trigger regular cli mode.

**Have you updated the necessary documentation?**
Will be updated right after the merge .

See https://github.com/rhd-gitops-example/docs

**Which issue(s) this PR fixes**:
https://issues.redhat.com/browse/GITOPS-251

2020-08-31 05:12 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> -type drivers []string
The code for supporting custom drivers has been removed. Can we revert it?

2020-08-31 13:08 UTC, chetan-rns requested changes

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> +	BootstrapExample = ktemplates.Examples(`
exported variables should have a comment. But why are these exported? Are we using them anywhere?

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> +	BootstrapLongDesc  = ktemplates.LongDesc(`Wizard GitOps CI/CD Manifest`)
Since it is integrated with flags. Should we drop the word wizard?

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> +// BootstrapParameters  encapsulates the parameters for the odo pipelines init command.
```suggestion
// BootstrapParameters encapsulates the parameters for the odo pipelines init command.
```
Extra whitespace

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> +	err = checkBootstrapDependencies(io, clientSet, log.NewStatus(os.Stdout))
Shouldn't we should check for mandatory flags before dependencies? Otherwise, we can only see the flag errors after the spinners have stopped

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> +	io.Overwrite = true
`overwrite` is always true in non-interactive mode. It should throw an error when the directory already exists

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> +			return fmt.Errorf("The mandatory flag %q has not been set", value)
```suggestion
			return fmt.Errorf("required flag(s) %q not set", value)
```
Just to keep the messages consistent between commands

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> +
```suggestion
```

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> +	io.Prefix = utility.MaybeCompletePrefix(io.Prefix)
I think these functions belong in `Complete()`. `initiateInteractiveMode()` already makes use of these functions in `Complete()`

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> +	if io.ServiceRepoURL != "" {
Is there any use case for this check? Either way, we have to call `Bootstrap()`

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap_test.go
> -		err := o.Complete("test", &cobra.Command{}, []string{"test", "test/repo"})
Shouldn't this unit test check `Complete()` as the name of the test suggests?

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap_test.go
> +			t.Errorf("Validate() %#v failed to match error: got %s, want %s", tt.name, err, tt.errMsg)
The error message should be corrected, since we're not checking `Validate()` here

2020-08-31 13:08 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap_test.go
>  func matchError(t *testing.T, s string, e error) bool {
Can we move these helper functions to the end?

2020-09-01 14:03 UTC, bigkevmcd approved these changes
Tested it locally, and it looks good to me.

2020-09-02 02:38 UTC, chetan-rns commented
@bigkevmcd @gaganhegde We're checking for mandatory flags after checking dependencies (spinners). Is this fine? Apart from that everything else looks good to me

2020-09-02 02:49 UTC, chetan-rns commented on pkg/odo/cli/pipelines/bootstrap.go
> +			return fmt.Errorf("The mandatory flag %q has not been set", value)
One last comment, we should probably keep the error messages consistent. Check the errors in other commands. Using `multierror` we can throw a single error for all the missing flags

2020-09-02 02:49 UTC, chetan-rns approved these changes

2020-09-02 13:27 UTC, bigkevmcd commented
> @bigkevmcd @gaganhegde We're checking for mandatory flags after checking dependencies (spinners). Is this fine? Apart from that everything else looks good to me

You can argue either way here, maybe moving the mandatory flags before spinners would be slightly nicer.

2020-09-02 16:59 UTC, merged