Improve the bootstrap output
rhd-gitops-example/odo pull request #183
Opened 2020-09-10 15:38 UTC by gaganhegde

**What type of PR is this?**
> /kind cleanup

**What does does this PR do / why we need it**:
Lists out the high-level process of events that occur during the bootstrap process.

See https://github.com/rhd-gitops-example/doc

**Which issue(s) this PR fixes**:
https://issues.redhat.com/browse/GITOPS-211
Fixes #?

2020-09-10 15:54 UTC, bigkevmcd requested changes

2020-09-10 15:54 UTC, bigkevmcd commented on pkg/pipelines/bootstrap.go
> +		log.Success("Service account Role-binding added to secrets")
I think this is a bit too low-level.

2020-09-10 15:54 UTC, bigkevmcd commented on pkg/pipelines/bootstrap.go
> +	log.Success("The default dev/stage environment have been created")
How about "Created the following environments: cicd, dev, stage" but with the namespaces for these environments?

2020-09-10 15:54 UTC, bigkevmcd commented on pkg/pipelines/bootstrap.go
> +		log.Success("Optional Pipelines tracker has been configured")
We can drop "Optional" here, as it is implied by the fact that we asked the user if they wanted it (or they explicitly configured it).

2020-09-10 15:54 UTC, bigkevmcd commented on pkg/pipelines/bootstrap.go
> +	log.Success("OpenShift Route has been configured")
```suggestion
	log.Success("OpenShift Route for the EventListener created")
```

2020-09-10 15:54 UTC, bigkevmcd commented on pkg/pipelines/bootstrap.go
> +		log.Success("The secrets have been encrypted")
How about "Authentication tokens encrypted in secrets" ?

2020-09-11 13:07 UTC, wtam2018 commented
@gaganhegde  We should probably do this PR in the new cli repo instead https://github.com/rhd-gitops-example/gitops-cli

2020-09-15 18:28 UTC, closed without merging