Add privileged scc to pipeline serviceaccount
rhd-gitops-example/odo pull request #35
Opened 2020-03-04 09:26 UTC by chetan-rns

**What type of PR is this?**

> /kind bug

**What does this PR do / why we need it**:

Added privileged SCC to the pipeline service account. 
Buildah requires privileged access to run the containers in privileged mode.

https://github.com/rhd-gitops-example/deployment-pipelines/blob/9a394126dbe4675df3c714706cdbc9addebc792e/bootstrap.sh#L58

2020-03-04 09:46 UTC, bigkevmcd commented
No test?

2020-03-04 10:22 UTC, chetan-rns commented
> No test?

Unit tests are already present at  https://github.com/rhd-gitops-example/odo/blob/bootstrap/pkg/pipelines/oc_adm_test.go. I just invoked the function from the bootstrap driver.

2020-03-04 20:25 UTC, wtam2018 commented
I thought pipeline operator would automatically setup pipeline service account including (what this PR does) adding privileged SCC to pipeline service account.  So, by using the pipeline service account created by the operator, we don't need to worry about adding privileged SCC to SA.   

Also, our odo pipeline bootstrap command should not be adding privileged SCC (at least without user's acknowledgement) when the user only wants to audit the generated yaml.

2020-03-04 20:30 UTC, wtam2018 requested changes
At first I thought pipeline operator would add the default sa (pipeline) to privileged SCC.  Unfortunately, that isn't the case.   It only adds the operator controller's sa to privileged SCC.    Using the default pipeline SA really does not buy us much.    It looks like we can't avoid having our odo command to invoke APIs to add SA to privileged SCC.

2020-03-05 14:15 UTC, bigkevmcd commented
Is there any way we can do this without having to make an explicit call to the server?

e.g. through additional (or modified) resources in the output?

Given that there's no requirement to actually apply the generated resources, it feels wrong for us to make an API call to a running server to make an authentication change for resources that may not be applied.

2020-03-05 14:38 UTC, wtam2018 commented
@bigkevmcd I believe scc can only be done with api calls.   A piece of good news is that @chetan-rns  found out that invoking cluster task buildah with operator installed does not need to add sa to scc privileged.    We just need to understand why it works.

2020-03-05 14:51 UTC, bigkevmcd commented
@wtam2018 Probably because of https://github.com/openshift/tektoncd-pipeline-operator/blob/0cf3108845ab6957df15f870de35016979bf4b1b/pkg/controller/config/config_controller.go#L250 ?

2020-03-05 15:00 UTC, wtam2018 commented
> @wtam2018 Probably because of https://github.com/openshift/tektoncd-pipeline-operator/blob/0cf3108845ab6957df15f870de35016979bf4b1b/pkg/controller/config/config_controller.go#L250 ?

We are not running on pipeline-controller SA.  If we were, it would've work for our local buildah as well.

2020-03-06 13:37 UTC, wtam2018 commented
This PR is no longer relevant as https://github.com/rhd-gitops-example/odo/pull/38 has been merged.

2020-03-06 13:37 UTC, closed without merging